-- Function: FUNCTION FUN_CONSULTARFOLIOVENTA()

-- DROP FUNCTION FUN_CONSULTARFOLIOVENTA()
--SELECT ifolioventa as folioventa from FUN_CONSULTARFOLIOVENTA()


CREATE OR REPLACE FUNCTION FUN_CONSULTARFOLIOVENTA()
   RETURNS TABLE(ifolioventa bigint) as
$BODY$
DECLARE
	
	
BEGIN
	RETURN QUERY SELECT last_value  FROM folioventa;
	
END;
$BODY$
LANGUAGE 'plpgsql' VOLATILE SECURITY DEFINER;