-- Function: FUNCTION FUN_CONSULTARFECHA()

-- DROP FUNCTION FUN_CONSULTARFECHA()
--SELECT cfecha as fecha from FUN_CONSULTARFECHA()


CREATE OR REPLACE FUNCTION FUN_CONSULTARFECHA()
   RETURNS TABLE(cfecha CHARACTER(10)) as
$BODY$
DECLARE
	
	cFechaDate 	DATE ;
BEGIN
	SELECT now()::date INTO cFechaDate;
	
	RETURN QUERY SELECT cFechaDate::CHARACTER(10);
	
END;
$BODY$
LANGUAGE 'plpgsql' VOLATILE SECURITY DEFINER;