-- Function: FUNCTION FUN_GRABARVENTA(INTEGER,INTEGER,CHARACTER,INTEGER,DATE,CHARACTER)

-- DROP FUNCTION FUN_GRABARVENTA(INTEGER,INTEGER,CHARACTER,INTEGER,DATE,CHARACTER)
--SELECT FUN_GRABARVENTA(5,2,'JOSE PEREZ',1200,'2018-01-01','ACTIVA')


CREATE OR REPLACE FUNCTION FUN_GRABARVENTA(INTEGER,INTEGER,CHARACTER,INTEGER,DATE,CHARACTER)
   RETURNS SMALLINT as
$BODY$
DECLARE
	iFolioVenta ALIAS FOR $1;
	iClave ALIAS FOR $2;
	cNombre ALIAS FOR $3;
	iTotal ALIAS FOR $4;
	cFecha ALIAS FOR $5;
	cEstatus ALIAS FOR $6;
	
	iEjecuto SMALLINT default 0;
	
BEGIN
	INSERT INTO cat_ventas(folioventa,clave,nombre,total,fecha,estatus) VALUES(iFolioVenta,iClave,cNombre,iTotal,cFecha,cEstatus);
	PERFORM nextval('folioventa');	
	
	iEjecuto = 1;
	
	RETURN iEjecuto;
	
END;
$BODY$
LANGUAGE 'plpgsql' VOLATILE SECURITY DEFINER;

